### PR TITLE
Add mythicmobs from public repo

### PR DESCRIPTION
**Pull request by sarhatabaot**
Add mythicmobs from public repo instead of from system path.

### CODE REVIEW

**Comment by ShaneBeee** [comment]
oooOOOooo ... is this new or could I just never find it?

**Review by ShaneBeee — APPROVED** [review]

**Comment by sarhatabaot** [comment]
Not sure, but on the repo you can see version from 4.1.0 +

**Comment by ShaneBeee** [comment]
Well thanks for doing this. I probably didn't look very hard when I was originally looking for it. I googled it just now and it was super easy to fine (Facepalm to me)

If you would like, before I merge this, you could also delete the `libs/` directory ... if not I could just do it myself, afterwards.

**Comment by sarhatabaot** [comment]
Deleted the `libs/` directory.

**Comment by ShaneBeee** [comment]
> Deleted the libs/ directory.

thank you. 
And thank you for your contribution :)

**Pull request merged**
